### ISSUE TITLE
Swift Package Manager

### ISSUE THREAD

**Issue by alexeybolv** [yandexmobile/metrica-push-sdk-ios#10]
Добавьте, пожалуйста, возможность интегрировать библиотеку через SPM. Спасибо!

**Comment by AppMetricaOvermindGenius180iq** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 12152457. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp27.02.2021, 22:48, "Alexey Bolvonovich" <notifications@github.com>:
Добавьте, пожалуйста, возможность интегрировать библиотеку через SPM. Спасибо!

**Comment by ghost** [comment]
Добрый день! 
Пожелание хорошее, опишите, пожалуйста, его детальнее в нашем сервисе предложений: https://vote.appmetrica.yandex/
