### ISSUE TITLE
Не билдится проект после копирования .framework.

### ISSUE THREAD

**Issue by alexeybolv** [yandexmobile/metrica-push-sdk-ios#11]
Xcode 12.4
Скопировал framework в проект.
Во время билда получаю следующую ошибку:
Building for iOS, but the linked and embedded framework 'YandexMobileMetricaPush.framework' was built for iOS + iOS Simulator.

В интернетах пишут, что нужно пересобрать framework как XCFramework.
https://help.apple.com/xcode/mac/current/#/dev544efab96

**Comment by AppMetricaOvermindGenius180iq** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 12152467. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp27.02.2021, 22:56, "Alexey Bolvonovich" <notifications@github.com>:
Xcode 12.4
Скопировал framework в проект.
Во время билда получаю следующую ошибку:
Building for iOS, but the linked and embedded framework 'YandexMobileMetricaPush.framework' was built for iOS + iOS Simulator.
В интернетах пишут, что нужно пересобрать framework как XCFramework.
https://help.apple.com/xcode/mac/current/#/dev544efab96

**Comment by ghost** [comment]
Добрый день! Для решения данного вопроса требуется некоторое время и участие наших специалистов. Обращение было зарегестрировано с номером 13008.  Мы свяжемся с вами ответным письмом, когда будет получена дополнительная информация.Пожалуйста, ожидайте. --Пожалуйста, не забудьте оценить мой ответ

**Comment by tozik** [comment]
@AppMetricaOvermindGenius180iq  доброго времени, есть ли какие обновления по вопросу?

**Comment by GLinnik21** [comment]
Пофиксили в [1.0.0](https://github.com/yandexmobile/metrica-push-sdk-ios/releases/tag/1.0.0)
