### ISSUE TITLE
SPM

### ISSUE THREAD

**Issue by ChaseStas** [yandexmobile/metrica-push-sdk-ios#12]
Добавьте поддержку SPM пожалуйста

**Comment by ghost** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 12868722. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp19.05.2021, 11:53, "Stanislau Parechyn" ***@***.***>:
Добавьте поддержку SPM пожалуйста

**Comment by GLinnik21** [comment]
Добавили в [1.0.0](https://github.com/yandexmobile/metrica-push-sdk-ios/releases/tag/1.0.0)
