### ISSUE TITLE
Невозможно отправить пуш-уведомление на тестовое устройство

### ISSUE THREAD

**Issue by EvgeLu** [yandexmobile/metrica-push-sdk-ios#2]
После интеграции в проект AppMetrica и MetricaPushSDK для iOS при попытке отправить на тестовый девайс пуш выдается ошибка "Для тестового устройства отсутствует токен, установите на тестовом устройстве и запустите приложение с интегрированным AppMetrica Push SDK". Перед отправкой приложение запускалось и по дебаггеру видно что при запуске
`[YMPYandexMetricaPush setDeviceTokenFromData:deviceToken];`
вызывается внутри 
`- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken`

При запуске тествого проекта для objective-c с установкой API_KEY от нашего приложения в AppMetrica ситуация повторяется. Выдается та же ошибка. 

IDFA от устройства получен с помощью приложения The Identifiers 

Тестировалось на ipod touch 5 ios v 9.3.5

**Comment by PiPhone** [comment]
Да, у меня такая же проблема.

**Comment by EvgeLu** [comment]
Сервис не поддерживает отправку пушей в Sandbox окружение. Чтобы устройство получало уведомление необходимо подписать проект Distribution-сертификатом, а не Development. Для того чтобы протестировать работу уведомлений через AppMetrica я собирал и устанавливал проект с AdHoc профилем через Fabric.

**Comment by bamx23** [comment]
Да, на данный момент Sandbox-окружение не поддерживается. Однако задача на данный функционал есть и поддержка появится в будущих релизах.

**Comment by anatoliykant** [comment]
Ждем...

**Comment by bamx23** [comment]
В релизе 0.5.0 поддержали новый метод, позволяющий вместе с пуш-токеном отправлять APNS-окружение. Примеры использования: [Swift](https://github.com/yandexmobile/metrica-push-sdk-ios/blob/master/Examples/Swift/YandexMobileMetricaPushSampleSwift/AppDelegate.swift#L76) и [ObjectiveC](https://github.com/yandexmobile/metrica-push-sdk-ios/blob/master/Examples/ObjectiveC/YandexMobileMetricaPushSampleObjC/MPSAppDelegate.m#L89).
К сожалению, сервер пока что не успел поддержать использование этой информации. Но лучше перевести ваш код на использование нового API заранее.

**Comment by anatoliykant** [comment]
Привет, Николай.
Отличные новости, сообщи, пожалуйста, когда сервер закроет эту задачу.

**Comment by bamx23** [comment]
Да, конечно

**Comment by squatchus** [comment]
Коллеги, а есть ли какие-то новости по проблеме? :)

**Comment by bamx23** [comment]
Пока что, к сожалению, новостей нет

**Comment by bamx23** [comment]
Недавно, наконец, поддержали возможность отправлять пуш в приложение с Sandbox APNs.
Для этого, как и писал выше, надо использовать специальный метод регистрации токена. 
Также учитывайте, что если у приложения на устройстве меняется APNs(отправляемый с токеном), то надо немного подождать, чтобы новое окружение прорасло в базе.

**Comment by yanushok** [comment]
Привет всем.
Проблема такая же как у ТС.
Версии библиотек последние, didRegisterForRemoteNotificationsWithDeviceToken срабатывает, ошибок нет, ios 14.6, подписывается distribution сертификатом, собирается как ad hoc.
Даже в одной из попыток ios устройство появилось в "аудитории" при создании push кампании. Но по прежнему "Для тестового устройства отсутствует токен, установите на тестовом устройстве и запустите приложение с интегрированным AppMetrica Push SDK".
Пытаюсь прикрутить к react-native, в нативной части приложения, без интерфейса в js.

**Comment by ghost** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 13200496. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp21.06.2021, 13:33, "Yan Yunitski" ***@***.***>:
Привет всем.
Проблема такая же как у ТС.
Версии библиотек последние, didRegisterForRemoteNotificationsWithDeviceToken срабатывает, ошибок нет, ios 14.6, подписывается distribution сертификатом, собирается как ad hoc.
Даже в одной из попыток ios устройство появилось в "аудитории" при создании push кампании. Но по прежнему "Для тестового устройства отсутствует токен, установите на тестовом устройстве и запустите приложение с интегрированным AppMetrica Push SDK".
Пытаюсь прикрутить к react-native, в нативной части приложения, без интерфейса в js.
