### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by abuharsky** [yandexmobile/metrica-push-sdk-ios#7]
Они через 50 лет добавят поддержку carthage, ловите, кому нужно:

https://github.com/abuharsky/yandexappmetrica

add to your carthage file

`binary "https://raw.githubusercontent.com/abuharsky/yandexappmetrica/master/YandexMobileMetricaPush.json"`

**Comment by bamx23** [comment]
Добрый вечер! В релизах тут, на Github, есть динамический фреймворк для Carthage.

**Comment by abuharsky** [comment]
проблема в том, что разработчики никак не могут добавить в своей проект, в конфигурационный cartfile, если вы не сделаете json файл с описанием.

Вот так это выглядит в carthfile, а по ссылке json с версиями библиотек и ссылками

binary "https://raw.githubusercontent.com/abuharsky/yandexappmetrica/master/YandexMobileMetricaPush.json"

**Comment by bamx23** [comment]
Спасибо за информацию. Такой вариант тоже поддержим.
Однако, сейчас попробовал старый вариант, [описаный в документации](https://tech.yandex.ru/appmetrica/doc/mobile-sdk-dg/tasks/ios-quickstart-docpage/), и Carthage справился, выкачав фреймворк, как положено. Для Push SDK в инструкции нет информации(поправим), но суть та же:
`github "yandexmobile/metrica-push-sdk-ios" ~> 0.7.2`

**Comment by bamx23** [comment]
JSON-файл с версиями выложил для основного SDK и Push SDK.
