### ISSUE TITLE
Не вызывается метод didReceiveRemoteNotification для своих пушей

### ISSUE THREAD

**Issue by lynx56** [yandexmobile/metrica-push-sdk-ios#8]
Добрый день, у меня есть такой кейс

Если использовать в качестве делегата UNUserNotificationCenter.current().delegate = YMPYandexMetricaPush.userNotificationCenterDelegate()
то приходящие с моего сервера пуши перестают попадать в метод 
func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any])

Фиксится тем что в приложении надо выставить background fetch capability и с сервера в пуши добавить "content-available":1 и тогда пуши можно обработать в 
func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void)
Ну либо реализацией UNUserNotificationCenterDelegate и вызовами оттуда сначала YMPUserNotificationCenterHandling, а потом обработку своих пушей. 
Можете как то прокоментировать, это так задумано или баг?

**Comment by bamx23** [comment]
Да, это ожидаемое поведение: при установке этого делегата пуши попадают в него.
Вы можете создать свой класс, реализующий [`UNUserNotificationCenterDelegate`](https://developer.apple.com/documentation/usernotifications/unusernotificationcenterdelegate), и выставить его  в [`nextDelegate`](https://appmetrica.yandex.ru/docs/mobile-sdk-dg/push/ios/swift/ref/YMPUserNotificationCenterDelegate.html#property_detail__property_nextDelegate) у `YMPYandexMetricaPush.userNotificationCenterDelegate()`.

**Comment by lynx56** [comment]
спасибо
