### ISSUE TITLE
application(_:didReceiveRemoteNotification:)

### ISSUE THREAD

**Issue by Algashev** [yandexmobile/metrica-push-sdk-ios#9]
Для чего вы используете в примере метод `application(_:didReceiveRemoteNotification:)`?
Согласно официальной документации [Apple](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623117-application):
> Implement the application(_:didReceiveRemoteNotification:fetchCompletionHandler:) method instead of this one whenever possible. If your delegate implements both methods, the app object calls the application(_:didReceiveRemoteNotification:fetchCompletionHandler:) method.

Метод `application(_:didReceiveRemoteNotification:fetchCompletionHandler:)` доступен начиная с iOS 7.0+, а в Podfile у вас указана поддержка начиная с iOS 8.

**Comment by bamx23** [comment]
Поддержка 7.0 была в более ранних версиях SDK. К тому же документация не противоречит тому, что допустимо использовать и старый метод, а значит нам надо показать, что обработку нотификаций надо производить и в нём.

**Comment by Algashev** [comment]
Учитывая, что начиная с iOS 11 метод имеет пометку, как `Deprecated` и мой предыдущий комментарий, похоже, что Ваш пример сильно устарел и нуждается в рефакторинге.

**Comment by bamx23** [comment]
Спасибо, поправим!

**Comment by Algashev** [comment]
Также хочу обратить внимание, что метод 
 `application(_:didReceiveRemoteNotification:fetchCompletionHandler:)` работает некорректно уже начиная с iOS 10:
- [https://forums.developer.apple.com/thread/54322](https://forums.developer.apple.com/thread/54322)
- [https://blog.kulman.sk/workaround-for-didreceiveremotenotification-not-called-in-ios11/](https://blog.kulman.sk/workaround-for-didreceiveremotenotification-not-called-in-ios11/)


Поэтому для версий iOS 10+ нужно применять методы `UNUserNotificationCenterDelegate` (см. [https://stackoverflow.com/questions/46758030/in-which-method-should-i-handle-ios-remote-notification?rq=1](https://stackoverflow.com/questions/46758030/in-which-method-should-i-handle-ios-remote-notification?rq=1)), а они у Вас в примере совсем не представлены.

**Comment by bamx23** [comment]
Делегаты представлены в примерах:
https://github.com/yandexmobile/metrica-push-sdk-ios/blob/f5525189e47d6bfb4ccc869833f87457eec3e62e/Examples/Swift/YandexMobileMetricaPushSampleSwift/AppDelegate.swift#L36
https://github.com/yandexmobile/metrica-push-sdk-ios/blob/f5525189e47d6bfb4ccc869833f87457eec3e62e/Examples/ObjectiveC/YandexMobileMetricaPushSampleObjC/MPSAppDelegate.m#L34

**Comment by Algashev** [comment]
Это я вижу. Я говорю о методах `UNUserNotificationCenterDelegate`:
``` swift
func userNotificationCenter(UNUserNotificationCenter, didReceive: UNNotificationResponse, withCompletionHandler: () -> Void)
```
``` swift
func userNotificationCenter(UNUserNotificationCenter, willPresent: UNNotification, withCompletionHandler: (UNNotificationPresentationOptions) -> Void)
```

**Comment by dzinad** [comment]
Вам необязательно реализовывать у себя эти методы, чтобы работал AppMetrica Push SDK, достаточно того, на что обратил внимание @bamx23. Вы можете реализовать эти методы у себя и передать вашего делегата в AppMetrica: `YMPYandexMetricaPush.userNotificationCenterDelegate().nextDelegate = yourDelegate`. Но это опционально.
Наш семпл демонстрирует только базовую интеграцию с AppMetrica Push SDK и не покрывает все возможные способы ее использования.
